import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import { UserProvider } from "@/components/AuthProvider/UserProvider";
import { ToastContainer } from "react-toastify";
import { CategoryProvider } from "@/components/AuthProvider/CategoryProvider";
import { FoodProvider } from "@/components/AuthProvider/FoodProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#404040]`}
      >
        <AuthProvider>
          <UserProvider>
            <CategoryProvider>
              <FoodProvider>{children}</FoodProvider>
            </CategoryProvider>
            <ToastContainer />
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
